version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "${DATABASE_URL}" # Pull from .env file
      SUPABASE_URL: "${SUPABASE_URL}" # Pull from .env file
      SUPABASE_KEY: "${SUPABASE_KEY}" # Pull from .env file
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate deploy && npx prisma generate && npm run start"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
